---
abstract: 'create models / views at load time'
author:
  - 'Tomas Doran (t0m) <bobtfish@bobtfish.net>'
  - 'Gianni Ceccarelli <gianni.ceccarelli@net-a-porter.com>'
build_requires:
  Catalyst: 0
  Catalyst::Runtime: 5.80
  Path::Class: 0
  Test::Deep: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-ComponentsFromConfig
no_index:
  directory:
    - t/lib
requires:
  Catalyst::Model: 0
  Catalyst::View: 0
  CatalystX::InjectComponent: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Role::Parameterized: 0
  MooseX::Traits::Pluggable: 0.10
  MooseX::Types::LoadableClass: 0
  MooseX::Types::Moose: 0
  namespace::autoclean: 0
version: 0.1_01
